gsap.from("h1",{
    y:10,
    opacity:0,
    delay:0.45,
    duration:0.85
  });
  gsap.from("h2",{
    y:7,
    opacity:0,
    delay:1.15,
    duration:0.8
  });
  gsap.from("img",{
    opacity:0,
    delay:0.25,
    duration:0.5
  });

  gsap.from(".red",{
    opacity:0,
    delay:2.35,
    duration:0.5
  });
  gsap.from(".red a",{
    opacity:0,
    delay:3.4,
    duration:0.5
  });
  gsap.from(".blue",{
    opacity:0,
    delay:4.5,
    duration:0.5
  });
  gsap.from(".blue a",{
    opacity:0,
    delay:5.4,
    duration:0.5
  });
  gsap.from(".para:nth-child(1)",{
    x:-35,
    opacity:0,
    delay:3.2,
    duration:0.75
  });
  gsap.from(".para:nth-child(2)",{
    x:35,
    opacity:0,
    delay:5.3,
    duration:0.75
  });
  